# Generated by Django 4.0.10 on 2024-08-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='core.productstock'),
        ),
    ]
