# Generated by Django 4.0.10 on 2024-08-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_product_stock_alter_productstock_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productstock',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock', to='core.productstock'),
        ),
    ]
